# Generated by Django 5.2.1 on 2025-05-11 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustbucket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the rustbucket was created'),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the rustbucket', null=True),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the rustbucket was last updated'),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the rustbucket', null=True),
        ),
    ]
