# Generated by Django 5.2.1 on 2025-05-11 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0002_rustbucket_created_at_rustbucket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='rustbucket',
            field=models.ForeignKey(blank=True, help_text='The rustbucket this alert belongs to (for backward compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='rustbucketregistry.rustbucket'),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, help_text='Alert severity (for backward compatibility)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, help_text='Alert source (for backward compatibility)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Alert timestamp (for backward compatibility)', null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='level',
            field=models.CharField(blank=True, help_text='Log level (for backward compatibility)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='rustbucket',
            field=models.ForeignKey(blank=True, help_text='The rustbucket this entry belongs to (for backward compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='rustbucketregistry.rustbucket'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], help_text='Type of alert', max_length=10),
        ),
        migrations.AlterField(
            model_name='honeypotactivity',
            name='type',
            field=models.CharField(choices=[('scan', 'Scan'), ('exploit', 'Exploit'), ('bruteforce', 'Brute Force'), ('malware', 'Malware'), ('SSH_BRUTEFORCE', 'SSH Brute Force')], help_text='Type of activity', max_length=20),
        ),
    ]
