# Generated by Django 5.2.1 on 2025-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0003_alert_rustbucket_alert_severity_alert_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeypotactivity',
            name='details',
            field=models.TextField(help_text='Details of the activity (string or JSON string)'),
        ),
    ]
