# Generated by Django 5.2.1 on 2025-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0004_alter_honeypotactivity_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypotactivity',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Activity type (for backward compatibility)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Source IP (for backward compatibility)', null=True),
        ),
    ]
