# Generated by Django 5.2.1 on 2025-05-11 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0005_honeypotactivity_activity_type_logentry_source_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Alert timestamp (for backward compatibility)'),
        ),
    ]
