# Generated by Django 5.2.1 on 2025-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0006_alter_alert_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rustbucket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Review', 'Review')], default='Review', help_text='Current status of the rustbucket', max_length=20),
        ),
    ]
