# Generated by Django 5.2.7 on 2025-10-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0008_rustbucket_token_alter_rustbucket_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rustbucket',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='rustbucket',
            name='description',
        ),
    ]
