# Generated by Django 5.2.7 on 2025-12-12 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0009_remove_rustbucket_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the notification channel', max_length=255)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook')], help_text='Type of notification channel', max_length=20)),
                ('config', models.JSONField(help_text='Configuration for the notification channel (email addresses, webhook URLs, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification channel is active')),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Minimum severity level to trigger notifications', max_length=10)),
                ('alert_types', models.JSONField(blank=True, default=list, help_text='List of alert types to notify on (empty = all types)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the notification channel was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the notification channel was last updated')),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['-created_at'],
            },
        ),
    ]
