# Generated by Django 5.2.7 on 2025-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0010_notificationchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustbucket',
            name='s3_access_key_id',
            field=models.CharField(blank=True, help_text='AWS access key ID for accessing the S3 bucket (optional for same-account access)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='s3_bucket_name',
            field=models.CharField(blank=True, help_text='S3 bucket name where this rustbucket stores logs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='s3_prefix',
            field=models.CharField(blank=True, default='logs/', help_text='Prefix/folder path in the S3 bucket where logs are stored', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='s3_region',
            field=models.CharField(blank=True, default='us-east-1', help_text='AWS region for the S3 bucket', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rustbucket',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, help_text='AWS secret access key (stored encrypted - use IAM roles in production)', max_length=255, null=True),
        ),
    ]
