# Generated by Django 5.2.7 on 2025-12-21 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0011_rustbucket_s3_access_key_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', help_text="User's role determining their access level", max_length=20)),
                ('all_rustbuckets_access', models.BooleanField(default=False, help_text='If True, user can access all rustbuckets regardless of specific assignments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('user', models.OneToOneField(help_text='The Django user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view', 'View Resource'), ('create', 'Create Resource'), ('update', 'Update Resource'), ('delete', 'Delete Resource'), ('resolve_alert', 'Resolve Alert'), ('grant_access', 'Grant Access'), ('revoke_access', 'Revoke Access'), ('change_role', 'Change User Role'), ('export', 'Export Data'), ('api_access', 'API Access')], help_text='The action performed', max_length=50)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource affected (e.g., 'rustbucket', 'alert', 'user')", max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the resource affected', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='rustbucketr_user_id_83c7d9_idx'), models.Index(fields=['action', 'timestamp'], name='rustbucketr_action_724605_idx'), models.Index(fields=['resource_type', 'resource_id'], name='rustbucketr_resourc_7788ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='RustbucketAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('manage', 'Manage (view + manage alerts)'), ('admin', 'Admin (full control)')], default='view', help_text='Level of access the user has to this rustbucket', max_length=20)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When access was granted')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The user who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
                ('rustbucket', models.ForeignKey(help_text='The rustbucket the user has access to', on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='rustbucketregistry.rustbucket')),
                ('user', models.ForeignKey(help_text='The user granted access', on_delete=django.db.models.deletion.CASCADE, related_name='rustbucket_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rustbucket Access',
                'verbose_name_plural': 'Rustbucket Access',
                'ordering': ['user__username', 'rustbucket__name'],
                'unique_together': {('user', 'rustbucket')},
            },
        ),
    ]
