# Generated by Django 5.2.7 on 2025-12-23 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0012_rbac_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view', 'View Resource'), ('create', 'Create Resource'), ('update', 'Update Resource'), ('delete', 'Delete Resource'), ('resolve_alert', 'Resolve Alert'), ('grant_access', 'Grant Access'), ('revoke_access', 'Revoke Access'), ('change_role', 'Change User Role'), ('export', 'Export Data'), ('api_access', 'API Access'), ('create_api_key', 'Create API Key'), ('revoke_api_key', 'Revoke API Key'), ('regenerate_api_key', 'Regenerate API Key')], help_text='The action performed', max_length=50),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, help_text='The API key value (auto-generated)', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Name/label for this API key (e.g., 'Production', 'Development')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active and can be used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this API key expires (null = never expires)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this API key was last used', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this API key has been used')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this API key was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this API key was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this API key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('rustbucket', models.ForeignKey(help_text='The rustbucket this API key authenticates', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='rustbucketregistry.rustbucket')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='rustbucketr_key_2cd392_idx'), models.Index(fields=['rustbucket', 'is_active'], name='rustbucketr_rustbuc_2b0f4f_idx')],
            },
        ),
    ]
