# Generated by Django 5.2.7 on 2025-12-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0013_alter_auditlog_action_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='source',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
    ]
