# Generated by Django 5.2.7 on 2025-12-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0014_remove_alert_backward_compat_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='rustbucket',
        ),
        migrations.RemoveField(
            model_name='honeypotactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='rustbucket',
        ),
    ]
