# Generated by Django 5.2.7 on 2025-12-24 00:56

from django.db import migrations, models


def convert_severity_to_lowercase(apps, schema_editor):
    """Convert uppercase severity values to lowercase."""
    Alert = apps.get_model('rustbucketregistry', 'Alert')

    # Convert severity values
    Alert.objects.filter(severity='HIGH').update(severity='high')
    Alert.objects.filter(severity='MEDIUM').update(severity='medium')
    Alert.objects.filter(severity='LOW').update(severity='low')

    # Convert type values if any are uppercase
    Alert.objects.filter(type='HIGH').update(type='error')
    Alert.objects.filter(type='MEDIUM').update(type='warning')
    Alert.objects.filter(type='LOW').update(type='info')


def convert_severity_to_uppercase(apps, schema_editor):
    """Reverse migration: convert lowercase severity values to uppercase."""
    Alert = apps.get_model('rustbucketregistry', 'Alert')

    Alert.objects.filter(severity='high').update(severity='HIGH')
    Alert.objects.filter(severity='medium').update(severity='MEDIUM')
    Alert.objects.filter(severity='low').update(severity='LOW')


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0015_remove_more_backward_compat_fields'),
    ]

    operations = [
        # First convert existing data
        migrations.RunPython(convert_severity_to_lowercase, convert_severity_to_uppercase),
        # Then alter the field definitions
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', help_text='Alert severity level', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], help_text='Type of alert', max_length=10),
        ),
    ]
