# Generated by Django 5.2.7 on 2025-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0017_convert_maintenance_to_inactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='logsink',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view', 'View Resource'), ('create', 'Create Resource'), ('update', 'Update Resource'), ('delete', 'Delete Resource'), ('resolve_alert', 'Resolve Alert'), ('grant_access', 'Grant Access'), ('revoke_access', 'Revoke Access'), ('change_role', 'Change User Role'), ('export', 'Export Data'), ('api_access', 'API Access'), ('create_api_key', 'Create API Key'), ('revoke_api_key', 'Revoke API Key'), ('regenerate_api_key', 'Regenerate API Key'), ('change_status', 'Change Status')], help_text='The action performed', max_length=50),
        ),
        migrations.AlterField(
            model_name='rustbucket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Review', 'Review')], default='Review', help_text='Current status of the rustbucket', max_length=20),
        ),
        migrations.DeleteModel(
            name='HoneypotActivity',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
