# Generated by Django 5.2.7 on 2025-12-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0018_remove_logentry_logsink_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
    ]
