# Generated by Django 5.2.7 on 2025-12-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0019_remove_notification_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rustbucket',
            name='s3_access_key_id',
        ),
        migrations.RemoveField(
            model_name='rustbucket',
            name='s3_secret_access_key',
        ),
    ]
