# Generated by Django 5.2.7 on 2025-12-25 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0020_remove_s3_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, help_text='The registration key value (auto-generated)', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Label for this key (e.g., 'Production honeypot 1')", max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the key was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this key expires (null = never expires)', null=True)),
                ('used', models.BooleanField(default=False, help_text='Whether this key has been used to register a rustbucket')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the key was used for registration', null=True)),
                ('revoked', models.BooleanField(default=False, help_text='Whether this key has been revoked by an admin')),
                ('created_by', models.ForeignKey(blank=True, help_text='The admin who created this key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_keys', to=settings.AUTH_USER_MODEL)),
                ('used_by_rustbucket', models.ForeignKey(blank=True, help_text='The rustbucket registered with this key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_key', to='rustbucketregistry.rustbucket')),
            ],
            options={
                'verbose_name': 'Registration Key',
                'verbose_name_plural': 'Registration Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='rustbucketr_key_e8e612_idx'), models.Index(fields=['used', 'revoked'], name='rustbucketr_used_e7b03f_idx')],
            },
        ),
    ]
