# Generated by Django 5.2.7 on 2025-12-26 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbucketregistry', '0021_registrationkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique identifier for the deployment', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this deployment (becomes rustbucket name)', max_length=255)),
                ('instance_id', models.CharField(blank=True, help_text='AWS EC2 instance ID once launched', max_length=50, null=True)),
                ('instance_type', models.CharField(default='t3.micro', help_text='EC2 instance type', max_length=50)),
                ('region', models.CharField(default='us-east-1', help_text='AWS region for deployment', max_length=50)),
                ('ami_id', models.CharField(blank=True, help_text='AMI used for deployment', max_length=50, null=True)),
                ('subnet_id', models.CharField(blank=True, help_text='VPC subnet for the instance', max_length=50, null=True)),
                ('security_group_id', models.CharField(blank=True, help_text='Security group for the instance', max_length=50, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, help_text='Public IP once assigned', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('launching', 'Launching'), ('running', 'Running'), ('registered', 'Registered'), ('failed', 'Failed'), ('terminated', 'Terminated')], default='pending', help_text='Current deployment status', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Additional status details or error message', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When deployment was initiated')),
                ('launched_at', models.DateTimeField(blank=True, help_text='When EC2 instance was launched', null=True)),
                ('registered_at', models.DateTimeField(blank=True, help_text='When rustbucket registered with registry', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who initiated deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to=settings.AUTH_USER_MODEL)),
                ('registration_key', models.OneToOneField(blank=True, help_text='Registration key for auto-registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment', to='rustbucketregistry.registrationkey')),
                ('rustbucket', models.OneToOneField(blank=True, help_text='Rustbucket created from this deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment', to='rustbucketregistry.rustbucket')),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
                'ordering': ['-created_at'],
            },
        ),
    ]
