"""
Django settings for rustbucketregistry project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-test-key-do-not-use-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rustbucketregistry.apps.RustbucketregistryConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rustbucketregistry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'rustbucketregistry' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rustbucketregistry.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for testing when USE_SQLITE env var is set or running tests
import sys
if os.getenv('USE_SQLITE') or 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# AWS S3 bucket configuration for log storage
AWS_S3_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME', 'rustbucket-logs')
AWS_S3_REGION = os.getenv('AWS_S3_REGION', 'us-east-1')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')

# Log processing configuration
LOG_PARSING_INTERVAL_HOURS = 1
LOG_ANALYSIS_INTERVAL_HOURS = 4

# Cache configuration for dashboard
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

# GeoIP configuration for IP geolocation
GEOIP_PATH = BASE_DIR / 'rustbucketregistry' / 'geoip'

# HTTPS/Security settings
# These are configurable via environment variables to support both HTTP and HTTPS deployments
# Set ENABLE_HTTPS=true when SSL is configured (e.g., via Let's Encrypt)
ENABLE_HTTPS = os.getenv('ENABLE_HTTPS', 'false').lower() in ('true', '1', 'yes')

if not DEBUG and ENABLE_HTTPS:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Scheduler task intervals (in minutes)
SCHEDULER_PULL_UPDATES_INTERVAL = int(os.getenv('SCHEDULER_PULL_UPDATES_INTERVAL', 5))
SCHEDULER_EXTRACT_LOGS_INTERVAL = int(os.getenv('SCHEDULER_EXTRACT_LOGS_INTERVAL', 15))
SCHEDULER_HEALTH_CHECK_INTERVAL = int(os.getenv('SCHEDULER_HEALTH_CHECK_INTERVAL', 10))

# Dashboard cache timeout (in seconds)
DASHBOARD_CACHE_TIMEOUT = int(os.getenv('DASHBOARD_CACHE_TIMEOUT', 60))

# Health check threshold (in minutes) - buckets not seen in this time are unhealthy
HEALTH_CHECK_THRESHOLD_MINUTES = int(os.getenv('HEALTH_CHECK_THRESHOLD_MINUTES', 15))

# =============================================================================
# EC2 Deployment Configuration
# =============================================================================

# Default instance configuration
EC2_DEFAULT_INSTANCE_TYPE = os.getenv('EC2_DEFAULT_INSTANCE_TYPE', 't3.micro')
EC2_DEFAULT_REGION = os.getenv('EC2_DEFAULT_REGION', 'us-east-1')

# Network configuration for deployed honeypots
EC2_VPC_ID = os.getenv('EC2_VPC_ID', '')
EC2_SUBNET_ID = os.getenv('EC2_SUBNET_ID', '')
EC2_SECURITY_GROUP_ID = os.getenv('EC2_SECURITY_GROUP_ID', '')
EC2_KEY_NAME = os.getenv('EC2_KEY_NAME', '')
EC2_IAM_INSTANCE_PROFILE = os.getenv('EC2_IAM_INSTANCE_PROFILE', '')

# Registry URL for honeypots to call back for registration
REGISTRY_BASE_URL = os.getenv('REGISTRY_BASE_URL', 'http://localhost:8000')

# Deployment limits (safety controls)
MAX_CONCURRENT_DEPLOYMENTS = int(os.getenv('MAX_CONCURRENT_DEPLOYMENTS', 10))

# RustBucket honeypot configuration
# LLM API keys - RustBucket supports OpenAI, Claude, Gemini, and Ollama
# Set the appropriate key for your chosen LLM provider
RUSTBUCKET_OPENAI_API_KEY = os.getenv('RUSTBUCKET_OPENAI_API_KEY', '')
RUSTBUCKET_ANTHROPIC_API_KEY = os.getenv('RUSTBUCKET_ANTHROPIC_API_KEY', '')
RUSTBUCKET_GOOGLE_API_KEY = os.getenv('RUSTBUCKET_GOOGLE_API_KEY', '')

# Docker image for RustBucket honeypot
RUSTBUCKET_DOCKER_IMAGE = os.getenv('RUSTBUCKET_DOCKER_IMAGE', 'jamesbinford/rustbucket:latest')
